title: "nix.ug"
subtitle: "Nix/NixOS User Group Directory"
logo: "logo.svg"

header: true
footer: '<p>Created with <span class="has-text-danger">❄️</span> using <a href="https://github.com/bastienwirtz/homer">Homer</a> and <a href="https://nixos.org/">Nix</a></i></a></p>'

theme: default
colors:
  light:
    highlight-primary: "#5277c3"
    highlight-secondary: "#5277c3"
    highlight-hover: "#7eb9e3"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#5277c3"
    highlight-secondary: "#5277c3"
    highlight-hover: "#7eb9e3"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

message:
  style: "is-dark"
  title: "What is a NUG?"
  icon: "fa fa-snowflake"
  content: "A Nix User Group (NUG) is a place where you can go to hang out with friends to learn about and use Nix. Typically this includes physical in-person meetups that happen regularly, though we catalogue online events too!"

links:
  - name: "Add a new NUG to this list"
    icon: "fas fa-square-plus"
    url: "https://github.com/nix-how/nix.ug#adding-a-new-user-group-to-the-list"

defaults:
  layout: list
  colorTheme: auto

services:
- items:
  - keywords: ''
    logo: assets/nix.camp/logo.png
    name: Nix.Camp
    subtitle: Yearly, often in Wales
    tag: United Kingdom/Wales
    target: _blank
    url: https://nix.camp/
  - keywords: ''
    logo: assets/nixcon/logo.png
    name: NixCon
    subtitle: Yearly, Europe
    tag: Europe
    target: _blank
    url: https://2022.nixcon.org/
  name: Events
- items:
  - icon: fas fa-snowflake
    keywords: online offline
    logo: ''
    name: Berlin NixOS Meetup
    subtitle: Thursdays Online, Tuesdays Offline
    tag: Germany
    target: _blank
    url: https://www.meetup.com/Berlin-NixOS-Meetup/
  - icon: ''
    keywords: online
    logo: assets/grenug/logo.svg
    name: Grenoble Nix User Group
    subtitle: No strict schedule
    tag: France
    target: _blank
    url: https://grenug.fr/
  - icon: fas fa-snowflake
    keywords: online
    logo: ''
    name: Nix Italia
    subtitle: No strict schedule
    tag: Italy
    target: _blank
    url: https://matrix.to/#/#it:nixos.org
  - icon: ''
    keywords: offline
    logo: assets/livnug/logo.svg
    name: Liverpool Nix User Group (LivNUG)
    subtitle: The first Thursday of each month at 7pm GMT
    tag: United Kingdom
    target: _blank
    url: https://liverpool.nix.ug
  - icon: fas fa-snowflake
    keywords: offline in-person
    logo: ''
    name: Madrid Nix / NixOS User Group
    subtitle: No strict schedule
    tag: Spain
    target: _blank
    url: https://www.meetup.com/madrid-nix-nixos-user-group
  - icon: fas fa-snowflake
    keywords: self hosted reddit
    logo: ''
    name: Silicon Valley Nix User Group
    subtitle: No strict schedule
    tag: America
    target: _blank
    url: https://www.svnix.com/
  - icon: ''
    keywords: offline in-person
    logo: assets/zurich/logo.png
    name: NixOS User Group Zürich
    subtitle: No strict schedule
    tag: Switzerland
    target: _blank
    url: https://www.meetup.com/NixOS-User-Group-Zurich/
  name: NUGs
